### ISSUE TITLE
Unable to initTerminal() if Location service is Off

### ISSUE THREAD

**Issue by jasonchong-xero** [stripe/stripe-terminal-android#401]
## Summary

Unable to initTerminal() if Location service is Off (Turning Location Service on the Phone). Is this by design? Is it possible still initialising the Terminal and defer the Location service check at the later stage? 

## Code to reproduce

1. Turn off Location Service on the Phone
2. Call Terminal.initTerminal()
3. I am getting Terminal Exception : LOCATION_SERVICES_DISABLED

## Android version

Android 13

## Impacted devices (Android devices or readers)

Samsung S22

## SDK version

3.1.0

**Comment by kekko7072** [comment]
I'm facing the same issue due to android device not able to have location. It's possible to have a fix or a workaround asap?

**Comment by chr-stripe** [comment]
We have implemented a fix for this internally and it will be available in our first SDK release of 2024. There is no way to work around this for now.

I will update this thread when the SDK release containing this change has been released.

**Comment by kekko7072** [comment]
Hi @chr-stripe happy new year 🥳. Can you tell me the period of rollout with this fix? Please i need it to plan the workload and plan the rollout. It very important for the company I work for.

**Comment by chr-stripe** [comment]
We expect to be releasing a new SDK version around the end of January.

**Comment by kekko7072** [comment]
> We expect to be releasing a new SDK version around the end of January.

Hi @chr-stripe any update on the release date? Thank you

**Comment by chr-stripe** [comment]
Hi all, we just released version `3.3.0` which should contain the fix for this issue. Thank you!

**Comment by kekko7072** [comment]
Hi @chr-stripe thank you so much for the release. I'm already using the new version. I was able to initialise terminal but now when i try to connect the terminal it fails because it's missing geolocation. Can i use the pos WisePad3 without Geolocation on the Android device? Because the board i'm using doesn't have it.

**Comment by chr-stripe** [comment]
Location is required to be available during payment collection, but to my knowledge this might still work even for hardware without a GPS chip; the location can be approximated by the Android OS just from the network alone. You may need to request _just_ `android.permission.ACCESS_COARSE_LOCATION`, but I believe the SDK will accept a coarse-grained network-inferred location if there is no physical GPS hardware on the device.

You may need to toggle location services on from the settings app on your Android device in order for the [`LocationManager.NETWORK_PROVIDER`](https://developer.android.com/reference/android/location/LocationManager#NETWORK_PROVIDER) to be enabled.

**Comment by kekko7072** [comment]
I have location enabled on the settings app of android and also give permission to location for the app i'm developing, added the android.permission.ACCESS_COARSE_LOCATION but i'm still getting the issue.

**Comment by chr-stripe** [comment]
Can you verify from your application if either of these location providers are enabled?

```kotlin
val locationManager = context.getSystemService(Context.LOCATION_SERVICE) as LocationManager

val hasGpsLocation = locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER)
val hasNetworkLocation = locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER)
```

If neither are enabled, there _any_ location providers that are enabled?

```kotlin
val enabledProviders = locationManager.getProviders(true)
```

**Comment by kekko7072** [comment]
I have Location (**settings**) enabled and Location (**for my application**) enabled. I've implemented this call, i get no GPS location and no Network Location. 
I tested `getProviders` and i get `ENABLED PROVIDERS: [passive]`.

What should i do?

**Comment by chr-stripe** [comment]
The SDK requires either the `gps` provider (if present) or the `network` provider to be enabled when discovering or interacting with readers. As far as I understand, the `passive` location provider simply returns the last known location as requested by other apps, which I assume will always be null if there are no other location providers available on the device. It's not clear to me if an external GPS Receiver would would for the SDK.

To reduce fraud risks associated with payments, and to minimize disputes, Stripe needs to know where payments occur. If the SDK can’t determine the location of the Android device, payments are disabled until location access is restored.

**Comment by scottfits** [comment]
@kekko7072 did you find a workaround here? running into the same issue with an embedded android tablet

**Comment by kekko7072** [comment]
> @kekko7072 did you find a workaround here? running into the same issue with an embedded android tablet

Yes i used MockLocation.
