### ISSUE TITLE
Turning bluetooth off while connected to a device doesn't fire `onUnexpectedReaderDisconnect` on Android 10

### ISSUE THREAD

**Issue by leaudro** [stripe/stripe-terminal-android#98]
## Summary
If I'm connected to a BBPOS device and I turn the phone's bluetooth off (i.e. on the notifications bar), the TerminalListener doesn't fire the `onUnexpectedReaderDisconnect` method. 

Also, the `Terminal` still holds information as if they were still connected, so if you call `connectionStatus` on a Terminal instance, it will return `ConnectionStatus.CONNECTED`, and `connectedReader` will return a Reader object that is not actually connected anymore (since Bluetooth is off)

PS: It works as intended on iOS -- The delegate method `didReportUnexpectedReaderDisconnect` is called. 

## Steps to reproduce it
1. Connect to a BBPOS device 
- `initTerminal` (with a `TerminalListener`) 
- `discoverReaders` + `connectReader`
2. Turn Bluetooth off
3. The `TerminalListener` set on initTerminal won't call `onUnexpectedReaderDisconnect`, and the Terminal instance will return status and reader as if it's still connected.

## Android version
I'm testing it on Android 10. (It seems to work just fine with Android 9)

## Impacted devices (Android devices or readers)
BBPOS Chipper 2X BT

## SDK version
1.0.8 (edit: I was using 1.0.2 before, but the problem persists on 1.0.8)

**Comment by chander-stripe** [comment]
@leaudro I'm unable to repro - can you try with the Kotlin example app we provide? I just tested with that, and the event seems to correctly fire.

I see the following in logcat:
```2020-02-26 16:54:51.597 10706-10706/com.stripe.example I/UnexpectedDisconnect: CHB204744003650```

**Comment by leaudro** [comment]
I've tried with the Kotlin example you provide, here's the Logcat:

```
com.stripe.example I/ConnectionStatusChange: CONNECTED
com.stripe.example W/.stripe.exampl: Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
com.stripe.example D/StripeTerminal: class=ConnectionTokenManager message=refreshToken
com.stripe.example D/StripeTerminal: class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
com.stripe.example I/.stripe.exampl: Explicit concurrent copying GC freed 475(39KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3149KB/6299KB, paused 75us total 20.667ms
com.stripe.example D/StripeTerminal: class=ApiClient message=generatePosRpcSession
com.stripe.example I/StripeTerminal: class=ApiClient api_request_id=req_BO4CC6rEi5vh3o
com.stripe.example D/StripeTerminal: class=ApiClient message=activateReader
com.stripe.example I/StripeTerminal: class=ApiClient api_request_id=req_6oSEMzodp6tut5
com.stripe.example I/StripeTerminal: class=TerminalSession reader_id=tmr_DlMP1w15hsgZ6Y
com.stripe.example D/StripeTerminal: class=TerminalListenerProxy message=onPaymentStatusChange(READY)
com.stripe.example I/PaymentStatusChange: READY
com.stripe.example D/LeakCanary: Watching instance of androidx.constraintlayout.widget.ConstraintLayout (com.stripe.example.fragment.discovery.DiscoveryFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 1d5ecc85-f858-489b-be4b-d15ef4e18bca
com.stripe.example D/LeakCanary: Watching instance of androidx.constraintlayout.widget.ConstraintLayout (com.stripe.example.fragment.discovery.DiscoveryFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key a90a2f38-509e-46e0-bae5-e358458b735b
com.stripe.example D/LeakCanary: Watching instance of com.stripe.example.fragment.discovery.DiscoveryFragment (com.stripe.example.fragment.discovery.DiscoveryFragment received Fragment#onDestroy() callback) with key cc02b487-c741-4158-9e7c-23857d04de19
com.stripe.example D/LeakCanary: Watching instance of com.stripe.example.fragment.discovery.DiscoveryFragment (com.stripe.example.fragment.discovery.DiscoveryFragment received Fragment#onDestroy() callback) with key a808a011-df81-4ccf-a077-cba8835d321c
com.stripe.example D/LeakCanary: Scheduling check for retained objects because found new object retained
com.stripe.example D/LeakCanary: Ignoring request to check for retained objects (found new object retained), already scheduled in 0ms
com.stripe.example D/LeakCanary: Ignoring request to check for retained objects (found new object retained), already scheduled in 0ms
com.stripe.example D/LeakCanary: Ignoring request to check for retained objects (found new object retained), already scheduled in -1ms
com.stripe.example D/LeakCanary: Ignoring check for retained objects scheduled because found new object retained: LeakCanary.Config.dumpHeap is false
com.stripe.example D/BluetoothAdapter: onBluetoothServiceDown: android.bluetooth.IBluetooth$Stub$Proxy@2a8e2da
com.stripe.example D/StripeTerminal: class=LogFlusher message="Reporting traces" num_traces=2
com.stripe.example D/StripeTerminal: class=LogFlusher message="Sent 2 traces"
com.stripe.example D/StripeTerminal: class=LogFlusher message="Reporting events" num_events=2
com.stripe.example D/StripeTerminal: class=LogFlusher message="Sent 2 events"
```

Notice that there are no signals of disconnection from Stripe's SDK, after Bluetooth is down, but only a log from `D/BluetoothAdapter: onBluetoothServiceDown:`

I've tested with a Pixel 3 and a Huawei Mate 20 pro phone, both running Android 10. 
However, on a Samsung Galaxy A10 running Android 9, I also couldn't reproduce the error. 
So I am editing the bug report and closing down on Android 10.

Thanks for the update. 
Let me know if you need any further information.

**Comment by chander-stripe** [comment]
Gotcha; I actually don't currently have an Android 10 device 😅 Let me borrow one from a friend and get back to you once I test with it, apologies for the delay.

**Comment by chander-stripe** [comment]
Ok, my pixel 3a arrived! :) I will test this week!

**Comment by chander-stripe** [comment]
Ok, confirmed it doesn't fire.

**Comment by leaudro** [comment]
Hi @chander-stripe! 

Do you have an idea of how long it would take to have an update of the SDK with this issue fixed? 
I am about to release the payment feature on my company's app, and I would like to plan accordingly in order to avoid this issue, or find some workaround, as more than half of our users are on Android 10. 

Thanks a lot!

**Comment by chander-stripe** [comment]
@leaudro - this is actually an issue with our hardware vendor's SDK (BBPOS) - I've filed a ticket with them accordingly, and they've yet to give me an ETA. Once they do I can update you.

If their ETA too long in the future, we can do a hacky fix on our side, but I'd prefer not to, if possible, until they get back to me on how long it'll take.

**Comment by chander-stripe** [comment]
@leaudro can you explain your use case better for me, so I can understand the urgency?

Theoretically you should be able to register a broadcast receiver and watch for bluetooth changes on your app side, until this BBPOS sdk fix comes in?

**Comment by leaudro** [comment]
Our beliefs in regards to the use case is that users will sporadically use the BBPOS, but the app can be kept on memory, and most of the users use their personal phones, so they might want to turn bluetooth off when not in use to save battery. 

The problem lies on the following scenario: The user connects to a BBPOS device, then he puts the app in background and turns Bluetooth off at some point. Whenever they come back to the app to proceed with another payment, not only the Terminal doesn't know that it's disconnected, but it also doesn't let the user disconnect from a device, or make payments. So what the user sees on the app is a connected device that doesn't do anything (and the device is not actually connected).

What happens is that the Terminal becomes unresponsive to any call after bluetooth is turned off and on again, and this cannot be solved by a BroadcastReceiver. 
The receiver will only help me on telling the user that they should restart the app, because that's the only way as of now that the BBPOS can start working again. 

PS: The app on background is not part of the problem, it's just how we imagine the scenario would be. On my tests, I just connect to a BBPOS, disconnect Bluetooth, reconnect it, and then nothing on the Terminal works anymore (the Terminal thinks it's still connect, but it doesn't disconnect, doesn't process payments, doesn't check for update... no further calls get a response)

**Comment by leaudro** [comment]
Hi @chander-stripe! Have you got any news from the hardware vendor?

**Comment by chander-stripe** [comment]
Hey! Sorry for the delay - they got back to me w/ an updated fix, and I'm testing out their new SDK to make sure it's fixed now. If all goes well, we can deploy v 1.0.18 the week of July 27th-ish.

**Comment by chander-stripe** [comment]
@leaudro I've confirmed this fix works. I have to polish up some code, but you can expect a fix pretty soon. You'll have to update your chipper firmware though.

**Comment by chander-stripe** [comment]
@leaudro looks like it works even without an SDK update, as long as you're on the new firmware.

If you send me a list of Chippers, I can put you on the new firmware version (1.00.03.43).

**Comment by chander-stripe** [comment]
@leaudro Ok, confirming that this works in v1.0.17 w/ chipper firmware 1.00.03.33 :) Let me know if that isn't the case, closing for now!

**Comment by leaudro** [comment]
Hi @chander-stripe,

Me and my team tested it with the firmware update on many different devices, and we found out that the problem persists, but we also found out something else: It works flawlessly on Samsung phones with Android 10, even before the firmware update. 

So, we tested it on Pixel phones, Huawei phones, and Samsung phones and tablets. I'm using the version 1.0.17 of the SDK. 
On Samsung devices, it worked well before and after the firmware update. 
On all non-Samsung devices, the problem persisted after the firmware update. 

So bottomline is the update didn't fix it, but we found out now that the problem happens only on a range of Android 10 devices. (I think we can for sure exclude Samsung devices)

**Comment by chander-stripe** [comment]
Ah interesting. I had only been testing on Samsung. One second, lemme test w/ Pixel today

**Comment by chander-stripe** [comment]
@leaudro what Chipper software version are you testing on? It looks like the bug you're describing is patched in version 1.00.03.43 onwards.

**Comment by chander-stripe** [comment]
Hmm, looks like there's been a regression. Reopening this issue

**Comment by chander-stripe** [comment]
@leaudro looks like this works on Android 11 though - I think it may be easier to just upgrade to Android 11 than waiting for hardware patches to this issue.

**Comment by malinajirka** [comment]
Hello @chander-stripe, Android 11 is available only on some Android devices. Moreover, we can't force end-users to update their OS. IMO this isn't an option for most consumers of the SDK. Is there any chance you could create a workaround within the SDK?

**Comment by billfinn-stripe** [comment]
Hi @malinajirka -- we're still working with our hardware vendor to identify and fix the underlying issue. In the meantime, we are working on a fix within our Android SDK that will ensure `onUnexpectedReaderDisconnect` does get called for this case.

**Comment by billfinn-stripe** [comment]
Hi @malinajirka -- we've released 2.0.0 which we believe fixes this issue. I'm going to optimistically close this issue, but feel free to re-open or raise a new one if you are still encountering problems.

**Comment by malinajirka** [comment]
Just FYI: This issue seems to be fixed in v1.0.22 -> migration to v2.x is not necessarily required.
